"""empty message

Revision ID: 07467d9d799a
Revises: 6ad768320d7e
Create Date: 2022-06-11 15:19:10.098289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07467d9d799a'
down_revision = '6ad768320d7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'image_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
