"""empty message

Revision ID: 990f990bdcf1
Revises: 5f729f2610f4
Create Date: 2022-06-11 14:17:19.127998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '990f990bdcf1'
down_revision = '5f729f2610f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.drop_column('Venue', 'looking_for_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('looking_for_talent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'seeking_talent')
    # ### end Alembic commands ###
